# Generated by Django 4.1.7 on 2023-04-24 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEPART',
            fields=[
                ('Nom', models.CharField(max_length=100)),
                ('NODEP', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('nomGrade', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('cd', models.AutoField(primary_key=True, serialize=False)),
                ('HCours', models.IntegerField()),
                ('NbHeure', models.IntegerField()),
                ('Niv', models.CharField(max_length=100)),
                ('MatSoi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jours',
            fields=[
                ('NumJour', models.IntegerField(primary_key=True, serialize=False)),
                ('NomJour', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('NbEtudlns', models.IntegerField()),
                ('Semestre', models.CharField(max_length=50)),
                ('Niv', models.CharField(max_length=100)),
                ('LibelleProfil', models.CharField(max_length=200)),
                ('codeProfil', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salles',
            fields=[
                ('NomSalles', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CapSal', models.IntegerField()),
                ('Niv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professeurs',
            fields=[
                ('Matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=50)),
                ('Telephone', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('sexe', models.TextField(max_length=50)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.grades')),
                ('Nodep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.depart')),
            ],
        ),
        migrations.CreateModel(
            name='PgmemptempsSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('J1', models.CharField(max_length=500)),
                ('J2', models.CharField(max_length=500)),
                ('J3', models.CharField(max_length=500)),
                ('J4', models.CharField(max_length=500)),
                ('J5', models.CharField(max_length=500)),
                ('J6', models.CharField(max_length=500)),
                ('Cd_Horaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.horaire')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.salles')),
            ],
        ),
        migrations.CreateModel(
            name='PgmemptempsPr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('J1', models.CharField(max_length=500)),
                ('J2', models.CharField(max_length=500)),
                ('J3', models.CharField(max_length=500)),
                ('J4', models.CharField(max_length=500)),
                ('J5', models.CharField(max_length=500)),
                ('J6', models.CharField(max_length=500)),
                ('Cd_Horaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.horaire')),
                ('Matricule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.professeurs')),
            ],
        ),
        migrations.CreateModel(
            name='Pgmemptemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('J1', models.CharField(max_length=500)),
                ('J2', models.CharField(max_length=500)),
                ('J3', models.CharField(max_length=500)),
                ('J4', models.CharField(max_length=500)),
                ('J5', models.CharField(max_length=500)),
                ('J6', models.CharField(max_length=500)),
                ('Cd_Horaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.horaire')),
                ('Noprfl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Matieres',
            fields=[
                ('Mat', models.CharField(max_length=200)),
                ('Nummat', models.IntegerField(primary_key=True, serialize=False)),
                ('Noprfl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.profil')),
            ],
        ),
        migrations.CreateModel(
            name='EmploisCours',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NatCours', models.CharField(max_length=50)),
                ('Cd_Horaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.horaire')),
                ('Mat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.matieres')),
                ('Matricule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.professeurs')),
                ('NOPRFL', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.profil')),
                ('NumJour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.jours')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emplois.salles')),
            ],
        ),
    ]
