# Generated by Django 4.2 on 2023-04-30 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Emplois", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emploiscours",
            name="Cd_Horaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.horaire"
            ),
        ),
        migrations.AlterField(
            model_name="emploiscours",
            name="Mat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.matieres"
            ),
        ),
        migrations.AlterField(
            model_name="emploiscours",
            name="Matricule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.professeurs"
            ),
        ),
        migrations.AlterField(
            model_name="emploiscours",
            name="NOPRFL",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.profil"
            ),
        ),
        migrations.AlterField(
            model_name="emploiscours",
            name="NumJour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.jours"
            ),
        ),
        migrations.AlterField(
            model_name="emploiscours",
            name="salle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.salles"
            ),
        ),
        migrations.AlterField(
            model_name="matieres",
            name="Noprfl",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.profil"
            ),
        ),
        migrations.AlterField(
            model_name="pgmemptemps",
            name="Cd_Horaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.horaire"
            ),
        ),
        migrations.AlterField(
            model_name="pgmemptemps",
            name="Noprfl",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.profil"
            ),
        ),
        migrations.AlterField(
            model_name="pgmemptempspr",
            name="Cd_Horaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.horaire"
            ),
        ),
        migrations.AlterField(
            model_name="pgmemptempspr",
            name="Matricule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.professeurs"
            ),
        ),
        migrations.AlterField(
            model_name="pgmemptempssi",
            name="Cd_Horaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.horaire"
            ),
        ),
        migrations.AlterField(
            model_name="pgmemptempssi",
            name="salle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.salles"
            ),
        ),
        migrations.AlterField(
            model_name="professeurs",
            name="Grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.grades"
            ),
        ),
        migrations.AlterField(
            model_name="professeurs",
            name="Nodep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Emplois.depart"
            ),
        ),
    ]
