# Generated by Django 4.2 on 2023-05-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emplois", "0003_alter_grades_id_alter_horaire_hcours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horaire",
            name="MatSoi",
        ),
        migrations.AddField(
            model_name="horaire",
            name="MatSoir",
            field=models.CharField(default="Matin", max_length=100),
        ),
    ]
