# Generated by Django 4.2 on 2023-05-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Emplois", "0004_remove_horaire_matsoi_horaire_matsoir"),
    ]

    operations = [
        migrations.CreateModel(
            name="Groupe",
            fields=[
                ("LibelleGroupe", models.CharField(max_length=200)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Noprfl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Emplois.profil"
                    ),
                ),
            ],
        ),
    ]
