# Generated by Django 4.2 on 2023-05-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Emplois", "0007_alter_matieres_nummat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emploiscours",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
