# Generated by Django 4.2 on 2023-05-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Emplois", "0009_alter_emploiscours_id_alter_horaire_hcours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horaire",
            name="Niv",
        ),
    ]
