# Generated by Django 4.1.7 on 2023-05-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0010_remove_horaire_niv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('Noniv', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='typeCours',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='professeurs',
            name='Matricule',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='Semestre',
        ),
        migrations.AddField(
            model_name='professeurs',
            name='NNI',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('NSem', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Niv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.niveau')),
            ],
        ),
        migrations.AddField(
            model_name='matieres',
            name='Sem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Emplois.semestre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='Niv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.niveau'),
        ),
    ]
