# Generated by Django 4.1.7 on 2023-06-05 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0012_anneeencours_emploiscours_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploiscours',
            name='NatCours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.typecours'),
        ),
    ]
