# Generated by Django 4.1.7 on 2023-06-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0013_alter_emploiscours_natcours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.CharField(max_length=50)),
                ('gen', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='matieres',
            name='CM',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matieres',
            name='PR',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matieres',
            name='TD',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matieres',
            name='TP',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matieres',
            name='Nummat',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DateJour',
            fields=[
                ('CDDateJour', models.AutoField(primary_key=True, serialize=False)),
                ('DateJour', models.DateField()),
                ('NumJour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.jours')),
                ('Semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.semaine')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('vl', models.BooleanField(default=False)),
                ('CDDateJour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.datejour')),
                ('NumJour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.jours')),
                ('cd_horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.horaire')),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.matieres')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.professeurs')),
                ('natcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.typecours')),
                ('noprfl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.profil')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.salles')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.semaine')),
            ],
        ),
    ]
