# Generated by Django 4.1.7 on 2023-06-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0014_semaine_matieres_cm_matieres_pr_matieres_td_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='annee',
            field=models.ForeignKey(default=2023, on_delete=django.db.models.deletion.CASCADE, to='Emplois.anneeencours'),
        ),
        migrations.AddField(
            model_name='professeurs',
            name='CompteBancaire',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
