# Generated by Django 4.1.7 on 2023-06-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0015_cours_annee_professeurs_comptebancaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploiscours',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emplois.anneeencours'),
        ),
    ]
