# Generated by Django 4.1.7 on 2023-06-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0017_alter_cours_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeencours',
            name='annee',
            field=models.IntegerField(),
        ),
    ]
