# Generated by Django 4.1.7 on 2023-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0018_alter_anneeencours_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeencours',
            name='annee',
            field=models.IntegerField(default=2023),
        ),
    ]
