# Generated by Django 4.1.7 on 2023-06-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0019_alter_anneeencours_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='annee',
            field=models.ForeignKey(default=2023, on_delete=django.db.models.deletion.CASCADE, to='Emplois.anneeencours'),
        ),
        migrations.AlterField(
            model_name='emploiscours',
            name='annee',
            field=models.ForeignKey(default=2023, on_delete=django.db.models.deletion.CASCADE, to='Emplois.anneeencours'),
        ),
    ]
