# Generated by Django 4.1.7 on 2023-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0021_alter_cours_annee_alter_emploiscours_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeencours',
            name='annee',
            field=models.IntegerField(),
        ),
    ]
