# Generated by Django 4.1.7 on 2023-06-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0022_alter_anneeencours_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploiscours',
            name='Semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Emplois.semestre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emploiscours',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
