# Generated by Django 4.1.7 on 2023-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0023_emploiscours_semestre_alter_emploiscours_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='type',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
