# Generated by Django 4.1.7 on 2023-06-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0024_semestre_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parite', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='semestre',
            name='parite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Emplois.typesemestre'),
            preserve_default=False,
        ),
    ]
