# Generated by Django 4.1.7 on 2023-06-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0025_typesemestre_semestre_parite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='Semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Emplois.semestre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semaine',
            name='annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Emplois.anneeencours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semaine',
            name='parite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Emplois.typesemestre'),
            preserve_default=False,
        ),
    ]
