# Generated by Django 4.1.7 on 2023-06-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emplois', '0026_cours_semestre_semaine_annee_semaine_parite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CM', models.IntegerField(default=3000)),
                ('TD', models.IntegerField(default=2000)),
                ('TP', models.IntegerField(default=2000)),
                ('PR', models.IntegerField(default=2000)),
            ],
        ),
    ]
